version: '3.9'

services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - /Users/ivanivaneichyk/www/smart-home/volumes
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=smart_home