apps:
  - name : 'script-worker'
    script: '/root/smart-home/application/worker.mjs'
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z'
  - name : 'app'
    script: '/root/smart-home/application/server.mjs'
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z'
