CREATE TABLE IF NOT EXISTS history (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  pv_power INTEGER NOT NULL DEFAULT 0,
  grid_status BOOLEAN NOT NULL DEFAULT 'f',
  grid_load INTEGER NOT NULL DEFAULT 0,
  home_load INTEGER NOT NULL DEFAULT 0,
  solar_radiation INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
